"""initial_schema

Revision ID: 2b5027c9ef6d
Revises: 
Create Date: 2026-05-13 14:27:56.214842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5027c9ef6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_addr', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('related_kind', sa.String(length=40), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_queue_related_kind'), ['related_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_queue_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_queue_status'), ['status'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('avatar_color', sa.String(length=7), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email_hash'), ['email_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('backup_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_destinations_machine_id'), ['machine_id'], unique=False)

    op.create_table('hardware_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('system_json', sa.Text(), nullable=True),
    sa.Column('cpu_json', sa.Text(), nullable=True),
    sa.Column('memory_json', sa.Text(), nullable=True),
    sa.Column('disks_json', sa.Text(), nullable=True),
    sa.Column('gpu_json', sa.Text(), nullable=True),
    sa.Column('motherboard_json', sa.Text(), nullable=True),
    sa.Column('devices_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id')
    )
    op.create_table('monitored_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon_key', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_services_machine_id'), ['machine_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('machine_offline', sa.Boolean(), nullable=False),
    sa.Column('service_down', sa.Boolean(), nullable=False),
    sa.Column('backup_failed', sa.Boolean(), nullable=False),
    sa.Column('backup_completed', sa.Boolean(), nullable=False),
    sa.Column('daily_summary', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_type', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('memory', sa.Float(), nullable=True),
    sa.Column('disk_used', sa.Float(), nullable=True),
    sa.Column('disk_free', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_metrics_timestamp'), ['timestamp'], unique=False)

    op.create_table('backup_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('schedule', sa.String(length=20), nullable=False),
    sa.Column('schedule_time', sa.String(length=5), nullable=False),
    sa.Column('compress', sa.Boolean(), nullable=False),
    sa.Column('verify_after', sa.Boolean(), nullable=False),
    sa.Column('encrypt', sa.Boolean(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_task_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['backup_destinations.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'name', name='uq_backup_job_machine_name')
    )
    with op.batch_alter_table('backup_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_jobs_machine_id'), ['machine_id'], unique=False)

    op.create_table('service_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['monitored_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_checks_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_checks_timestamp'), ['timestamp'], unique=False)

    op.create_table('backup_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('files_done', sa.Integer(), nullable=False),
    sa.Column('bytes_done', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes_estimate', sa.BigInteger(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('backup_full_name', sa.String(length=200), nullable=True),
    sa.Column('backup_path', sa.String(length=500), nullable=True),
    sa.Column('job_name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('backup_type_snapshot', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backup_jobs.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_started_at'), ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_machine_id'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_job_id'))

    op.drop_table('backup_runs')
    with op.batch_alter_table('service_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_checks_timestamp'))
        batch_op.drop_index(batch_op.f('ix_service_checks_service_id'))

    op.drop_table('service_checks')
    with op.batch_alter_table('backup_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_jobs_machine_id'))

    op.drop_table('backup_jobs')
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_metrics_timestamp'))

    op.drop_table('system_metrics')
    op.drop_table('services')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('monitored_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_services_machine_id'))

    op.drop_table('monitored_services')
    op.drop_table('hardware_snapshots')
    with op.batch_alter_table('backup_destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_destinations_machine_id'))

    op.drop_table('backup_destinations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email_hash'))

    op.drop_table('users')
    op.drop_table('machines')
    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_queue_status'))
        batch_op.drop_index(batch_op.f('ix_email_queue_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_email_queue_related_kind'))

    op.drop_table('email_queue')
    # ### end Alembic commands ###
